---
AWSTemplateFormatVersion: 2010-09-09
Description: ECS task role for the comms delivery service

Parameters:
  Environment:
    Type: String
    AllowedValues: [ uat, prd ]

Conditions:
  IsProd: !Equals [ !Ref Environment, "prd" ]

Resources:

  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        -
          PolicyName: read-aiven-bucket
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
                - 's3:Get*'
                - 's3:List*'
              Resource:
                - 'arn:aws:s3:::ovo-comms-aiven'
                - 'arn:aws:s3:::ovo-comms-aiven/*'
        -
          PolicyName: read-credstash
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
                - 'kms:Decrypt'
              Resource:
                - !Sub "arn:aws:kms:eu-west-1:${AWS::AccountId}:key/*"
            - Effect: Allow
              Action:
                - 'dynamodb:GetItem'
                - 'dynamodb:Query'
              Resource:
                - !Sub "arn:aws:dynamodb:eu-west-1:${AWS::AccountId}:table/credential-store"
        -
          PolicyName: read-pdf-bucket
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
                - 's3:Get*'
                - 's3:List*'
              Resource:
                - !Sub 'arn:aws:s3:::${Environment}-ovo-comms-pdfs'
                - !Sub 'arn:aws:s3:::${Environment}-ovo-comms-pdfs/*'
        -
          PolicyName: read-write-dynamo-table
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:Put*'
                - 'dynamodb:Update*'
                - 'dynamodb:Query'
                - 'dynamodb:Scan'
                - 'dynamodb:Get*'
                - 'dynamodb:List*'
                - 'dynamodb:BatchGetItem'
                - 'dynamodb:DescribeTable'
              Resource:
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${CommRecordTable}*"
        -
          PolicyName: read-template-summary-table
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:Query'
                - 'dynamodb:Get*'
              Resource:
                Fn::ImportValue:
                  TemplateSummaryTableArn # <- Exported from Template manager cloudformation.yml
        -
          PolicyName: read-comms-content
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
                - "s3:Get*"
                - "s3:List*"
              Resource:
                - !Sub "arn:aws:s3:::ovo-comms-rendered-content-${Environment}"

  CommRecordTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: hashedComm
        AttributeType: S
      KeySchema:
      - AttributeName: hashedComm
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: !If [ IsProd, 10, 5 ]
        WriteCapacityUnits: !If [ IsProd, 10, 5 ]

  CommRecordTableReadCapacityAlarm:
      Type: "AWS::CloudWatch::Alarm"
      Properties:
        ComparisonOperator: GreaterThanOrEqualToThreshold
        Namespace: "AWS/DynamoDB"
        Dimensions:
          - Name: TableName
            Value: !Ref CommRecordTable
        MetricName: ConsumedReadCapacityUnits
        AlarmActions:
          - !ImportValue "CloudwatchPagerDutyTopic"
        OKActions:
          - !ImportValue "CloudwatchPagerDutyTopic"
        Period: 60
        EvaluationPeriods: 3
        Statistic: Sum
        Threshold: 550

  CommRecordTableWriteCapacityAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Namespace: "AWS/DynamoDB"
      Dimensions:
        - Name: TableName
          Value: !Ref CommRecordTable
      MetricName: ConsumedWriteCapacityUnits
      AlarmActions:
        - !ImportValue "CloudwatchPagerDutyTopic"
      OKActions:
        - !ImportValue "CloudwatchPagerDutyTopic"
      Period: 60
      EvaluationPeriods: 3
      Statistic: Sum
      Threshold: 550