version: '2'

services:

  delivery-service:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.eu-west-1.amazonaws.com/delivery-service:0.1-SNAPSHOT
    depends_on:
      - kafka
      - mockServer
    links:
      - kafka
      - mockServer:api.mailgun.net
      - mockServer:api.twilio.com
    environment:
      ENV: LOCAL
      KAFKA_HOSTS: kafka:29092
      MAILGUN_DOMAIN: "mailgun@email.com"
      MAILGUN_API_KEY: "my_super_secret_api_key"
      MAILGUN_HOST: "http://api.mailgun.net:1080"
      TWILIO_HOST: "http://api.twilio.com:1080"

  zookeeper:
    image: confluentinc/cp-zookeeper:3.1.1
    ports:
      - "32181:32181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:3.1.1
    ports:
     - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${IP_ADDRESS}:29092
    depends_on:
      - zookeeper

  mockServer:
    image: jamesdbloom/mockserver
    ports:
      - "1080:1080"